---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  name: jellyfin-secrets
  namespace: jellyfin
spec:
  encryptedData:
    JELLYFIN__DEFAULTADMINPASSWORD: AgAT4V3gQULZMyEjd36/IpPJkqvJmrvDlSUH4G2NlVpXvV55IuemtZekgrWPjkHZxuJlJxYtwPqblPNL3yg58ZH/ivBQIPmaKSMbE+uyI/fdYC2WgMOOjYCftWI31WqYAGiPmFUwhojS29NNzW48mDHXB9xVIP47ICb07sb8Dwx5DaYlQnTuZAKbO1o0FDXao7btyG3apuTRKoldIiY7EM0B2NoqDPfoAl+HU2PnQMQR60Zn8l1Bm/lw8euIKW3goxpOvaAqrZhDakOhX1Xk2J7CDv5R7IovP9miAQzDznCfjwbx0THw0hwr4TjmMIW1hBu50NZUJtltJVRJfDFVxlJ33/Lf7EP95V+vBFDxPhQdUMpcToUmMuhcJrwdIZLgn7i0yRcZlzCTwUhAlagZtotn+9MUdR0I9Iua9+pRGVV+BJfKs6uW2aIsJIwRbZ4IpQiw0Y2REkPAnILwbhpa76zCnxw2BPJ14SxtD/KTGRhye+ngkyZQbJBkBidumntLjd/g0mgXE25jAcztfyu0ZiZt/kMri82qxTPqmwatqM4AgfkQQog+j1waSSPR/3wRNi53kh6rIZZNw7WkcQE9fqlD5RUOtC81G8fSpoYxzqGmz8iNQrCL5+r+U5A2VZbsR2SBh7BJ/QFhopO5lPM4K+ISVZnYkId1lCLVgq4RwcuxDZwyTkRnKAV4JN7KriDWeYYNGzDFLlRVoho=
  template:
    metadata:
      name: jellyfin-secrets
      namespace: jellyfin
    type: Opaque
