---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-prometheus-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
