---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwrt
  namespace: openwrt
  labels:
    app.kubernetes.io/name: openwrt
    app.kubernetes.io/instance: openwrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openwrt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openwrt
        app.kubernetes.io/instance: openwrt
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: openwrt
          image: openwrt/rootfs:23.05.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: overlay
              mountPath: /overlay
            - name: etc
              mountPath: /etc
      volumes:
        - name: overlay
          persistentVolumeClaim:
            claimName: openwrt-overlay
        - name: etc
          configMap:
            name: openwrt-etc
