---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwrt-overlay
  namespace: openwrt
  labels:
    app.kubernetes.io/name: openwrt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
